controller_joint_names: ['base_link_to_fl_wheel_joint', 'base_link_to_fr_wheel_joint', 'base_link_to_br_wheel_joint', 'base_link_to_bl_wheel_joint', 'base_link_to_yaw_joint', 'base_link_to_pitch_joint', ]
